### PR TITLE
Update to 3.0.0-RC1

### PR DESCRIPTION
**Pull request by shin-sakata**

### CODE REVIEW

**Review by joroKr21 — APPROVED** [review]

**Comment by eed3si9n** [comment]
FYI sbt 1.5.0-M1 doesn't support `doc` for RC1, but there's a fix merged on develop - https://github.com/sbt/sbt/issues/6307

**Comment by SethTisue** [comment]
we shouldn't merge this until we can also bump sbt-dotty to 0.5.3 (they're publishing it now)

**Comment by shin-sakata** [comment]
they've published sbt-dotty 0.5.3, so I've fixed the commit.

**Comment by SethTisue** [comment]
@shin-sakata how you closed this? it looked ready for merge?

**Comment by SethTisue** [comment]
thank you!

**Pull request merged**
