### PR TITLE
feat(github actions): adding in github actions for ci instead of trav…

### PR DESCRIPTION
**Pull request by brbrown25**
…is. #38.

### CODE REVIEW

**Comment by brbrown25** [comment]
with this it should be relatively easy to do #36 and #37 by adding the workflow steps and then running the generate command

**Comment by nicolasstucki** [comment]
Let's wait until we have updated this project to 3.0.0-RC2 until we merge this pull request.

**Comment by nicolasstucki** [comment]
We should also not delete `.travis.yml` in this PR. We can delete it later.

**Comment by brbrown25** [comment]
> We should also not delete `.travis.yml` in this PR. We can delete it later.

I've updated to not remove the travis file,

**Review by nicolasstucki — APPROVED** [review]

**Pull request merged**
