### PR TITLE
Add parenthesis to side-effecting method

### PR DESCRIPTION
**Pull request by barryoneill**
Per https://docs.scala-lang.org/scala3/book/methods-most.html#a-suggestion-about-methods-that-take-no-parameters

### CODE REVIEW

**Comment by xuwei-k** [comment]
> CLA check for barryoneill failed
Please sign the Scala CLA to contribute to the Scala compiler.
Go to https://www.lightbend.com/contribute/cla/scala and then
comment on the pull request to ask for a new check.


https://github.com/scala/scala3.g8/actions/runs/7645919364/job/20833957687?pr=132#step:3:21

**Comment by barryoneill** [comment]
please check again

**Comment by eed3si9n** [comment]
Reran the check. It seems to pass now.

**Comment by barryoneill** [comment]
Thanks!

**Pull request merged**
